/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulangan.atm;

import javax.swing.JOptionPane;


/**
 *
 * @author Nabil Rizki
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bExit = new javax.swing.JButton();
        iSaldo = new javax.swing.JButton();
        Tranfer = new javax.swing.JButton();
        Penarikan = new javax.swing.JButton();
        Penyetoran = new javax.swing.JButton();
        Bantuan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Penarikan");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 180, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("LAKUKAN TRANSAKSI");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 10, 170, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Exit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 180, 100, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Transfer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 130, 60, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Informasi Saldo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 80, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Penyetoran");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 80, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Bantuan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 130, 100, 20);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(60, 40, 260, 250);

        bExit.setText("<");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel2.add(bExit);
        bExit.setBounds(10, 220, 40, 23);

        iSaldo.setText(">");
        iSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iSaldoActionPerformed(evt);
            }
        });
        jPanel2.add(iSaldo);
        iSaldo.setBounds(330, 120, 40, 23);

        Tranfer.setText(">");
        Tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranferActionPerformed(evt);
            }
        });
        jPanel2.add(Tranfer);
        Tranfer.setBounds(330, 170, 40, 23);

        Penarikan.setText(">");
        Penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenarikanActionPerformed(evt);
            }
        });
        jPanel2.add(Penarikan);
        Penarikan.setBounds(330, 220, 40, 23);

        Penyetoran.setText("<");
        Penyetoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PenyetoranActionPerformed(evt);
            }
        });
        jPanel2.add(Penyetoran);
        Penyetoran.setBounds(10, 120, 40, 23);

        Bantuan.setText("<");
        Bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanActionPerformed(evt);
            }
        });
        jPanel2.add(Bantuan);
        Bantuan.setBounds(10, 170, 40, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 380, 340);

        setSize(new java.awt.Dimension(396, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iSaldoActionPerformed
        // TODO add your handling code here:
        int saldo = 100000000;
        JOptionPane.showMessageDialog(null,"Saldo anda saat ini sebesar Rp "+saldo);
    }//GEN-LAST:event_iSaldoActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Terimakasih telah melakukan transaksi di ATM ");
        dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void PenyetoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenyetoranActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Penyetoran().setVisible(true);
    }//GEN-LAST:event_PenyetoranActionPerformed

    private void TranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranferActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Transfer().setVisible(true);
    }//GEN-LAST:event_TranferActionPerformed

    private void BantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Bantuan().setVisible(true);
    }//GEN-LAST:event_BantuanActionPerformed

    private void PenarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PenarikanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Penarikan().setVisible(true);
    }//GEN-LAST:event_PenarikanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton Penarikan;
    private javax.swing.JButton Penyetoran;
    private javax.swing.JButton Tranfer;
    private javax.swing.JButton bExit;
    private javax.swing.JButton iSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
