/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulangan.atm;

import javax.swing.JOptionPane;

/**
 *
 * @author Nabil Rizki
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarik = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tranfer2 = new javax.swing.JButton();
        Tranfer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(null);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TRANSFER");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 0, 170, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MASUKKAN NOMINAL");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 30, 170, 40);
        jPanel2.add(tarik);
        tarik.setBounds(50, 70, 190, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Rp.");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 70, 18, 30);

        jButton1.setText("TRANFER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 110, 90, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("TRANSAKSI LAIN?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 130, 170, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("IYA");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(240, 160, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("TIDAK");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(240, 190, 60, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(50, 40, 300, 220);

        Tranfer2.setText(">");
        Tranfer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tranfer2ActionPerformed(evt);
            }
        });
        jPanel1.add(Tranfer2);
        Tranfer2.setBounds(360, 200, 40, 23);

        Tranfer.setText(">");
        Tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TranferActionPerformed(evt);
            }
        });
        jPanel1.add(Tranfer);
        Tranfer.setBounds(360, 230, 40, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 310);

        setSize(new java.awt.Dimension(425, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tf = tarik.getText();
        int saldo = 100000000;
        int jmltf = Integer.parseInt(tf);
        int total = saldo-jmltf;
       if(jmltf%100!=0)
           JOptionPane.showMessageDialog(null, "Mesin ATM BCA Tidak Bisa mengirim uang koin\nSilahkan Ulangi lagi","Transaksi Gagal",0);
       else{
           if (jmltf>saldo)
               JOptionPane.showMessageDialog(null,"Saldo Anda Tidak Mencukupi \nSilahkan Lakukan Pengisian Ulang","Transaksi Gagal",0);
           else if(jmltf<50000)
               JOptionPane.showMessageDialog(null,"Besaran MInimum Pengiriman adalah Rp 50000","Transaksi Gagal",0);
           else{
               saldo = saldo-jmltf;
               JOptionPane.showMessageDialog(null,"Saldo Anda Saat Ini Sebesar : "+saldo);
               if(saldo<=50000)
               JOptionPane.showMessageDialog(null, "Saldo minimal harus Rp 50000,segera lakukan penyetoran untuk menghindari penutupan akun","CAUTION",2);
               
           }
       }     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Tranfer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tranfer2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Home().setVisible(true);

    }//GEN-LAST:event_Tranfer2ActionPerformed

    private void TranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TranferActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Terimakasih telah melakukan transaksi di ATM ");
        dispose();
    }//GEN-LAST:event_TranferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tranfer;
    private javax.swing.JButton Tranfer2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tarik;
    // End of variables declaration//GEN-END:variables
}
